config/routes.rb
PerformanceCurve::Application.routes.draw do
  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  resources :fatigues
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  

end

app/models/fatigue.rb
class Fatigue < ActiveRecord::Base
  validates :user_id, :fatigue, presence: true
  validates :fatigue, numericality: {greater_than_or_equal_to: 0}
  validates :fatigue, numericality: {less_than_or_equal_to: 100}
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authorize
  protect_from_forgery

  private

  protected

    def authorize
      unless User.find_by_id(session[:user_id])
        redirect_to login_url, notice: "Please log in"
      end
    end
end

app/controllers/fatigues_controller.rb
class FatiguesController < ApplicationController
  # GET /fatigues
  # GET /fatigues.json
  def index
    @fatigues = Fatigue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fatigues }
    end
  end

  # GET /fatigues/1
  # GET /fatigues/1.json
  def show
    @fatigue = Fatigue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fatigue }
    end
  end

  # GET /fatigues/new
  # GET /fatigues/new.json
  def new
    @fatigue = Fatigue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fatigue }
    end
  end

  # GET /fatigues/1/edit
  def edit
    @fatigue = Fatigue.find(params[:id])
  end

  # POST /fatigues
  # POST /fatigues.json
  def create
    @fatigue = Fatigue.new(params[:fatigue])

    respond_to do |format|
      if @fatigue.save
        format.html { redirect_to @fatigue, notice: 'Fatigue was successfully created.' }
        format.json { render json: @fatigue, status: :created, location: @fatigue }
      else
        format.html { render action: "new" }
        format.json { render json: @fatigue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fatigues/1
  # PUT /fatigues/1.json
  def update
    @fatigue = Fatigue.find(params[:id])

    respond_to do |format|
      if @fatigue.update_attributes(params[:fatigue])
        format.html { redirect_to @fatigue, notice: 'Fatigue was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @fatigue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fatigues/1
  # DELETE /fatigues/1.json
  def destroy
    @fatigue = Fatigue.find(params[:id])
    @fatigue.destroy

    respond_to do |format|
      format.html { redirect_to fatigues_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to fatigues_url
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url, notice: "Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url,
          notice: "User #{@user.name} was successfully created." }
        format.json { render json: @user,
          status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url,
          notice: "User #{@user.name} was successfully updated." }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fatigues_helper.rb
module FatiguesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fatigues/_form.html.erb
<%= form_for(@fatigue) do |f| %>
  <% if @fatigue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fatigue.errors.count, "error") %> prohibited this fatigue from being saved:</h2>

      <ul>
      <% @fatigue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :fatigue %><br />
    <%= f.number_field :fatigue %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fatigues/edit.html.erb
<h1>Editing fatigue</h1>

<%= render 'form' %>

<%= link_to 'Show', @fatigue %> |
<%= link_to 'Back', fatigues_path %>

app/views/fatigues/index.html.erb
<h1>Listing fatigues</h1>

<table>
  <tr>
    <th>User</th>
    <th>Fatigue</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fatigues.each do |fatigue| %>
  <tr>
    <td><%= fatigue.user_id %></td>
    <td><%= fatigue.fatigue %></td>
    <td><%= link_to 'Show', fatigue %></td>
    <td><%= link_to 'Edit', edit_fatigue_path(fatigue) %></td>
    <td><%= link_to 'Destroy', fatigue, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fatigue', new_fatigue_path %>

app/views/fatigues/new.html.erb
<h1>New fatigue</h1>

<%= render 'form' %>

<%= link_to 'Back', fatigues_path %>

app/views/fatigues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @fatigue.user_id %>
</p>

<p>
  <b>Fatigue:</b>
  <%= @fatigue.fatigue %>
</p>


<%= link_to 'Edit', edit_fatigue_path(@fatigue) %> |
<%= link_to 'Back', fatigues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PerformanceCurve</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<div class="performance_curve_form">

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <legend>Enter User Details</legend>

  <div>
    <%= f.label :name %>:
    <%= f.text_field :name, size: 40 %>
  </div>

  <div>
    <%= f.label :password, 'Password' %>:
    <%= f.password_field :password, size: 40 %>
  </div>

  <div>
    <%= f.label :password_confirmation, 'Confirm' %>:
    <%= f.password_field :password_confirmation, size: 40 %>
  </div>

  <div>
    <%= f.submit %>
  </div>

  </fieldset>
<% end %>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>

<table>
	<tr>
		<th>Name</th>
		<th>Password digest</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>

	<% @users.each do |user| %>
	<tr>
		<td><%= user.name %></td>
		<td><%= user.password_digest %></td>
		<td><%= link_to 'Show', user %></td>
		<td><%= link_to 'Edit', edit_user_path(user) %></td>
		<td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
	</tr>
	<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>